name: Libft CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  norminette:
    name: Norminette Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install norminette
        run: |
          python3 -m pip install --upgrade pip
          pip install norminette

      - name: Run norminette
        run: norminette

  libft_check:
    name: Libft Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y make gcc

      - name: Run libft_check
        run: |
          chmod +x libft_check.sh
          ./libft_check.sh

  francinette:
    name: Francinette Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y git make gcc clang

      - name: Clone Francinette
        run: |
          git clone https://github.com/xicodomingues/francinette.git
          cd francinette
          ./setup.sh

      - name: Run Francinette
        run: |
          cd francinette
          ./grademe.sh --bonus
