name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  libft-test:
    runs-on: ubuntu-latest.
    defaults:
      run:
        working-directory: libft
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y make gcc

      - name: Run tests
        run: |
          cd libftTester
          make 
    
  build-image:
    runs-on: ubuntu-latest
    needs: [libft-test]
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}

    strategy:
      matrix:
        component: [libft-test]

    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with: 
          context: ${{ matrix.component }}
          file: ${{ matrix.component }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/spm-${{ matrix.component }}:${{ github.ref_name }}
    