name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  libft-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y make gcc

      - name: Run tests
        run: |
          working-directory: libft
          cd libftTester
          make 