name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y make gcc

      - name: Compile libft
        run: |
          cd libft
          make

      - name: Run tests Part1
        run: |
          cd ../tests/Part1_functions
          cc -o test_part1 *.c -L../../libft -lft
          ./test_part1

      - name: Run tests Part2
        run: |
          cd ../tests/Part2_functions
          cc -o test_part2 *.c -L../../libft -lft
          ./test_part2

      - name: Run tests Additional
        run: |
          cd ../tests/Additional_functions
          cc -o test_additional *.c -L../../libft -lft
          ./test_additional

      - name: Run tests Bonus
        run: |
          cd ../tests/Bonus_functions
          cc -o test_bonus *.c -L../../libft -lft
          ./test_bonus

